name: kyber
description: Kyber Post-Quantum Key exchange protocol
version: 0.0.1
homepage: https://github.com/aldrinsartfactory/kyber-dart
repository: https://github.com/aldrinsartfactory/kyber-dart

environment:
  sdk: '>=2.16.1 <3.0.0'


dependencies:
  sha3: ^0.2.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.20.1
